### ISSUE TITLE
A- Realizar encuestas a los usuarios sobre a la forma de pago.

### ISSUE THREAD

**Issue by Aylintania00** [Yislein/PruebaSoftware#63]
A1-  Formular preguntas para la encuesta.

A2- Realizar encuesta a los usuarios.

A3- Analizar los resultados e implementarlas en el proyecto.

**Comment by Yislein** [comment]
[A1 - Encuesta formas de pago comedor.docx](https://github.com/Yislein/PruebaSoftware/files/15004900/A1.-.Encuesta.formas.de.pago.comedor.docx)

**Comment by Yislein** [comment]
[A2 - Form Encuesta.txt](https://github.com/Yislein/PruebaSoftware/files/15004901/A2.-.Form.Encuesta.txt)

**Comment by Yislein** [comment]
[A3 - Boletos - Comedor UACM (respuestas).ods](https://github.com/Yislein/PruebaSoftware/files/15004902/A3.-.Boletos.-.Comedor.UACM.respuestas.ods)

**Comment by JonasMart369** [comment]
[Resultados de la encuenta analizados.xlsx](https://github.com/Yislein/PruebaSoftware/files/15071735/Resultados.de.la.encuenta.analizados.xlsx)
