### ISSUE TITLE
B- Intercambiar información con el área encargado de la universidad sobre el tipo de compras en línea.

### ISSUE THREAD

**Issue by Aylintania00** [Yislein/PruebaSoftware#64]
B1 – Presentación del proyecto de pagos en línea.

B2 – Planificación de capacitación y comunicación.

**Comment by JonasMart369** [comment]
B1 – Presentación del proyecto de pagos en línea.
[Presentación del proyecto de pagos en línea.pdf](https://github.com/Yislein/PruebaSoftware/files/15072302/Presentacion.del.proyecto.de.pagos.en.linea.pdf)

**Comment by JonasMart369** [comment]
B2 – Planificación de capacitación y comunicación.
