### ISSUE TITLE
C- Consulta de información con los bancos.

### ISSUE THREAD

**Issue by Aylintania00** [Yislein/PruebaSoftware#65]
C1 – Identificación de necesidades y objetivos.

C2 – Intercambio seguro de información.

**Comment by Yislein** [comment]
[C - Azteca_Negocio.pdf](https://github.com/Yislein/PruebaSoftware/files/15173057/C.-.Azteca_Negocio.pdf)

> - Investigación hecha en "Banco Azteca" para la apertura de una "cuenta comercial" para el deposito de las compras en líneas de los boletos del proyecto comedor, en donde todas deberán ser creadas por una apertura de $1000, y en donde no requiere exactamente el nombre de alguna empresa o en este caso la UACM, y donde la apertura puede hacerse con el nombre de algún integrante del proyecto o empresa. Y en donde el saldo mensual puede variar entre $3000 en las diferentes cuentas disponibles.
