### ISSUE TITLE
D- Capacitar a programadores en seguridad cibernética.

### ISSUE THREAD

**Issue by Aylintania00** [Yislein/PruebaSoftware#66]
Consta de 2 partes de un curso sobre ciberseguridad, en donde tendremos que implementar en el proyecto del comedor.
 
D1 – Seguridad en desarrollo web y protección de datos.

D2 – Seguridad de transacciones en línea y gestión de sesiones.

D3 – Autenticación de usuarios y generación de boletos QR.

D4 – Protección de privacidad y detección de actividades sospechosas

+Nota--"Generación QR":  Esta en sí, el servidor que usaremos, nos generará automáticamente el QR, solo tendremos que integrar el "Google Wallet" a la pagina web.

**Comment by Yislein** [comment]
[Primera parte - Curso_Ciberseguridad.docx](https://github.com/Yislein/PruebaSoftware/files/15004917/Primera.parte.-.Curso_Ciberseguridad.docx)

Primera parte del curso. Queda pendiente subir la siguiente parte.

**Comment by Yislein** [comment]
[Segunda parte - Curso_Ciberseguridad.docx](https://github.com/Yislein/PruebaSoftware/files/15215739/Segunda.parte.-.Curso_Ciberseguridad.docx)
 Segunda parte del curso. Por subir la tercera y ultima parte.

**Comment by Yislein** [comment]
[Tercera parte - Curso_Ciberseguridad.docx](https://github.com/Yislein/PruebaSoftware/files/15215742/Tercera.parte.-.Curso_Ciberseguridad.docx)
Ultima parte del curso.
