### ISSUE TITLE
E- Capacitación sobre la recopilación segura de datos personales. 

### ISSUE THREAD

**Issue by Aylintania00** [Yislein/PruebaSoftware#67]
E1 – Seguridad de los datos personales.

E2 – Normativas y regulaciones de protección de datos.

E3 – Prácticas de recopilación y almacenamiento de datos.

E4 – Gestión de incidentes de seguridad

**Comment by Yislein** [comment]
[E - Datos_Personales.docx](https://github.com/Yislein/PruebaSoftware/files/15005018/E.-.Datos_Personales.docx)

**Comment by Yislein** [comment]
[E - Curso_Normatividad_Legislacion.pdf](https://github.com/Yislein/PruebaSoftware/files/15172985/E.-.Curso_Normatividad_Legislacion.pdf)

* Materia tomada en el 8° semestre, en donde el propósito general es que el estudiante distinga, explique y aplique las normas y regulaciones vigentes en el campo de la informática, para administrar proyectos relacionados con la creación o utilización del software, en este caso aplicándola en el proyecto en curso de la página web comedor.
