### ISSUE TITLE
F- FreeSqlDataBase

### ISSUE THREAD

**Issue by Aylintania00** [Yislein/PruebaSoftware#68]
F1-Verificar la documentación de FreeSqlDataBase para la gestion de la DB

F2-Verificar si es compatible el hosting utilizado para conectarlo con FrreSql

F3-Conectar el modulo usuario con la DB

F4-Agregar la seguridad a la DB

F5-Agregar el codigo PHP del generador de QR

F6- Prototipo

**Comment by JonasMart369** [comment]
F1-Verificar la documentación de FreeSqlDataBase para la gestión de la DB

**Comment by JonasMart369** [comment]
F3-Conectar el modulo usuario con la DB

**Comment by JonasMart369** [comment]
F4-Agregar la seguridad a la DB

**Comment by JonasMart369** [comment]
F5-Agregar el código PHP del generador de QR

**Comment by JonasMart369** [comment]
F6- Prototipo
