### ISSUE TITLE
G - Modificación en la documentación.

### ISSUE THREAD

**Issue by Aylintania00** [Yislein/PruebaSoftware#69]
G1 – Revisión de la documentación ya existente.

G2 – Documentación de los cambios realizados.

G3 – Comunicación de los cambios.

**Comment by JonasMart369** [comment]
G1 – Revisión de la documentación ya existente.

**Comment by crisantojimemezsalomon** [comment]
[SRS comedor.v1.1.docx](https://github.com/Yislein/PruebaSoftware/files/15113517/SRS.comedor.v1.1.docx)

**Comment by Aylintania00** [comment]
G2 – Documentación de los cambios realizados.

[SDD_2.docx](https://github.com/Yislein/PruebaSoftware/files/15475581/SDD_2.docx)

**Comment by Aylintania00** [comment]
G3 – Comunicación de los cambios.

Los cambios realizados fueron los siguientes:

- Se actualizaron los diagramas de la documentación en los que se incluyeron, el generador de los QR.
- La modificación de la base de datos.
- La seguridad e intercambio seguro de la información.
- La actualización de la interfaz.
