### ISSUE TITLE
H- Reuniones de trabajo con el equipo desarrollador	.

### ISSUE THREAD

**Issue by Aylintania00** [Yislein/PruebaSoftware#70]
H1 – Definición de objetivos y alcances del proyecto.

H2 – Planificación y coordinación.

H3 – Identificar problemas y posibles soluciones.

H4 – Reuniones de trabajo con los desarrolladores.

H5 – Establecer un seguimiento a las acciones acordadas

* Determinación de objetivos
* Alcance de las tareas
* Cronograma 
* Establecimiento de presupuesto
* Contemplación del proyecto desde el inicio hasta su conclusión. 
Etapas, inicio, planificación, ejecución, supervisión y conclusión.

**Comment by JonasMart369** [comment]
H5 – Establecer un seguimiento a las acciones acordadas
Esta será una herramienta, el cual será fundamental para el desarrollo del modulo de pagos en linea de la pagina web del comedor de la UACM, aplicando el seguimiento y sus análisis posterior de las acciones acordadas para poder llegar al éxito de las acciones y tareas de la organización.
1. En la terminación de cada acción o tarea que se lleva por semana será necesario medir y comunicar los resultados,  implementando las encuestas de pulso para poder  obtener una respuestas rápida con datos específicos y procesables.
Estos resultados serán comunicados de manera simple y positiva, resaltando como se solucionara el desafío enfrentado o como se logro solucionar dicho desafío, entregando sus hitos y referencias para poder tener el aprendizaje y retroalimentación sobre cada aspecto realizado.
2. Se realizara el seguimiento de éxito de los planes de acción o las acciones frente los resultados. Esto para que exista un registro constaste de seguimiento, ingresando esta información en la documentación de los cambios realizados, si es necesario se tendrá que automatizar el proceso a través de una herramienta que nos permita visualizar y comprar resultados.
3. Por ultimo tanto el Scrum Master como el Product Owner podrán contemplar los factores que impactaron d manera positiva o negativa a los colaboradores, permitiendo hacer un comparativo entre el antes y después de los planes de acción a través de encuestas y evoluciones de clima laboral y desempeño.

**Comment by JonasMart369** [comment]
H1 – Definición de objetivos y alcances del proyecto.

**Comment by JonasMart369** [comment]
H2 – Planificación y coordinación.
Se establecerán los objetivos específicos del proyecto mediante las premisas de seguridad de la información recabada, seguridad y eficiencia en los pagos.
Se identificaran detalladamente los requisitos del sistema agregando sus funcionalidades necesarias, la seguridad requerida, intercambio seguro de información.
-En la parte del diseño del modulo se tendrá un análisis detallado del sistema de información, contemplando su arquitectura técnica, interfaces de usuario y las especificaciones de seguridad, para garantizar que el modulo cumpla con los requisitos identificados para poder brindar una experiencia de usuario intuitiva y segura.
-En el desarrollo e implementación se llevara a cabo un fase de desarrollo del modulo, donde se podrá construir las diferentes funcionalidades y su implementación de la infraestructura necesaria. Se podrá un énfasis especial en la implementación de medidas de seguridad robustas para garantizar el intercambio seguro de información.
Las pruebas y evaluación del modulo se realizaran de una manera rigurosa esto para poder identificar y corregir posibles fallos o vulnerabilidades de seguridad, se creara un modulo en el cual se encontrara una encuesta de satisfacción esto para poder obtener la retroalimentación sobre la usabilidad y funcionalidad del sistema.
Por ultimo tendremos el mantenimiento y mejora continua estableciendo un plan para poder garantizar el funcionamiento continuo del modulo de pago, también se planificaran actualizaciones periódicas para mejorar la seguridad y funcionalidad del modulo de pago en respuesta a cambios en las necesidades de la UACM o avances tecnológicos.

**Comment by JonasMart369** [comment]
H3 – Identificar problemas y posibles soluciones.

**Comment by JonasMart369** [comment]
H4 – Asignar tareas y responsabilidades.

**Comment by JonasMart369** [comment]
H5 – Establecer un seguimiento a las acciones acordadas
Esta será una herramienta, el cual será fundamental para el desarrollo del modulo de pagos en linea de la pagina web del comedor de la UACM, aplicando el seguimiento y sus análisis posterior de las acciones acordadas para poder llegar al éxito de las acciones y tareas de la organización.

En la terminación de cada acción o tarea que se lleva por semana será necesario medir y comunicar los resultados, implementando las encuestas de pulso para poder obtener una respuestas rápida con datos específicos y procesables.
Estos resultados serán comunicados de manera simple y positiva, resaltando como se solucionara el desafío enfrentado o como se logro solucionar dicho desafío, entregando sus hitos y referencias para poder tener el aprendizaje y retroalimentación sobre cada aspecto realizado.
Se realizara el seguimiento de éxito de los planes de acción o las acciones frente los resultados. Esto para que exista un registro constaste de seguimiento, ingresando esta información en la documentación de los cambios realizados, si es necesario se tendrá que automatizar el proceso a través de una herramienta que nos permita visualizar y comprar resultados.
Por ultimo tanto el Scrum Master como el Product Owner podrán contemplar los factores que impactaron d manera positiva o negativa a los colaboradores, permitiendo hacer un comparativo entre el antes y después de los planes de acción a través de encuestas y evoluciones de clima laboral y desempeño.
